version: '3.8'

services:
  app:
    image: automaticbytes/demo-app
    ports:
      - "3100:3100"
    container_name: demo-app

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
    volumes:
      - .:/usr/src/app
    environment:

      - BASE_URL=http://host.docker.internal:3100
    container_name: home-test-ui